#############################################################################
# Makefile for building: project05
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sun Dec 4 21:37:32 2016
# Project:  project05.pro
# Template: app
# Command: /usr/local/software/qt4/bin/qmake -o Makefile project05.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/software/qt-4.8.6/mkspecs/linux-g++-64 -I. -I/usr/local/software/qt-4.8.6/include/QtCore -I/usr/local/software/qt-4.8.6/include/QtGui -I/usr/local/software/qt-4.8.6/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/software/qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/usr/local/software/qt-4.8.6/lib -lQtGui -Wl,-rpath,/usr/local/software/qt4/lib -L/usr/local/software/qt4/lib -L/usr/X11R6/lib64 -Wl,-rpath,/usr/local/software/qt4/lib -Wl,-rpath,/usr/local/software/qt4/lib -lQtCore -Wl,-rpath,/usr/local/software/qt4/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/software/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = html_table.cpp \
		html_utility.cpp \
		register.cpp \
		register_common.cpp \
		register_course.cpp \
		register_course_management.cpp \
		register_course_registration.cpp \
		register_course_selection.cpp \
		register_file_management.cpp \
		register_menu.cpp \
		register_report_management.cpp \
		register_student.cpp \
		register_student_management.cpp \
		register_system.cpp 
OBJECTS       = html_table.o \
		html_utility.o \
		register.o \
		register_common.o \
		register_course.o \
		register_course_management.o \
		register_course_registration.o \
		register_course_selection.o \
		register_file_management.o \
		register_menu.o \
		register_report_management.o \
		register_student.o \
		register_student_management.o \
		register_system.o
DIST          = /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		project05.pro
QMAKE_TARGET  = project05
DESTDIR       = 
TARGET        = project05

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project05.pro  /usr/local/software/qt-4.8.6/mkspecs/linux-g++-64/qmake.conf /usr/local/software/qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/release.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf \
		/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/software/qt-4.8.6/lib/libQtGui.prl \
		/usr/local/software/qt-4.8.6/lib/libQtCore.prl
	$(QMAKE) -o Makefile project05.pro
/usr/local/software/qt-4.8.6/mkspecs/common/unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/linux.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/software/qt-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/software/qt-4.8.6/mkspecs/qconfig.pri:
/usr/local/software/qt-4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_pre.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/release.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/default_post.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/shared.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/qt.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/moc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/resources.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/uic.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/yacc.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/lex.prf:
/usr/local/software/qt-4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/software/qt-4.8.6/lib/libQtGui.prl:
/usr/local/software/qt-4.8.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project05.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project051.0.0 || $(MKDIR) .tmp/project051.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project051.0.0/ && $(COPY_FILE) --parents checker.h deque.h hashmap.h html_table.h html_utility.h register_common.h register_course.h register_course_selection.h register_menu.h register_student.h register_system.h regularExpression.h sortlist.h term.h .tmp/project051.0.0/ && $(COPY_FILE) --parents html_table.cpp html_utility.cpp register.cpp register_common.cpp register_course.cpp register_course_management.cpp register_course_registration.cpp register_course_selection.cpp register_file_management.cpp register_menu.cpp register_report_management.cpp register_student.cpp register_student_management.cpp register_system.cpp .tmp/project051.0.0/ && (cd `dirname .tmp/project051.0.0` && $(TAR) project051.0.0.tar project051.0.0 && $(COMPRESS) project051.0.0.tar) && $(MOVE) `dirname .tmp/project051.0.0`/project051.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project051.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

html_table.o: html_table.cpp html_table.h \
		html_utility.h \
		deque.h \
		register_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o html_table.o html_table.cpp

html_utility.o: html_utility.cpp html_utility.h \
		deque.h \
		register_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o html_utility.o html_utility.cpp

register.o: register.cpp register_common.h \
		term.h \
		register_system.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register.o register.cpp

register_common.o: register_common.cpp register_common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_common.o register_common.cpp

register_course.o: register_course.cpp register_common.h \
		register_course.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_course.o register_course.cpp

register_course_management.o: register_course_management.cpp register_common.h \
		register_system.h \
		term.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_course_management.o register_course_management.cpp

register_course_registration.o: register_course_registration.cpp register_common.h \
		register_system.h \
		term.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_course_registration.o register_course_registration.cpp

register_course_selection.o: register_course_selection.cpp register_common.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_course_selection.o register_course_selection.cpp

register_file_management.o: register_file_management.cpp register_common.h \
		register_system.h \
		term.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_file_management.o register_file_management.cpp

register_menu.o: register_menu.cpp register_common.h \
		register_menu.h \
		term.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_menu.o register_menu.cpp

register_report_management.o: register_report_management.cpp register_common.h \
		register_system.h \
		term.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h \
		html_utility.h \
		deque.h \
		html_table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_report_management.o register_report_management.cpp

register_student.o: register_student.cpp register_common.h \
		register_student.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_student.o register_student.cpp

register_student_management.o: register_student_management.cpp register_common.h \
		register_system.h \
		term.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_student_management.o register_student_management.cpp

register_system.o: register_system.cpp register_common.h \
		register_system.h \
		term.h \
		sortlist.h \
		hashmap.h \
		checker.h \
		regularExpression.h \
		register_menu.h \
		register_student.h \
		register_course.h \
		register_course_selection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register_system.o register_system.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

